% script_inputPipeProperties

i = 1;
    j=1;
    pipe(i,j).tag = 'L1';
    pipe(i,j).c  = 1000; % wave speed
    pipe(i,j).D  = 0.2;  % diameter
    pipe(i,j).f  = 0.02; % friction factor
    pipe(i,j).Nx = 400; % number of reaches
    j=2;
    pipe(i,j).tag = 'L1A';
    pipe(i,j).c  = 1000; % wave speed
    pipe(i,j).D  = 0.2;  % diameter
    pipe(i,j).f  = 0.02; % friction factor
    pipe(i,j).Nx = 400; % number of reaches 
i = 2;
    j=1;
    pipe(i,j).tag = 'L2';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 500;
    j=2;
    pipe(i,j).tag = 'L2A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 500;
    %pipe(i).startNode = 4;
    %pipe(i).endNode = 5;
i = 3;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 700;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 700;
i = 4;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 50;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 26;
i = 5;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 50;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 50;
i = 6;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 1200;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 800;
i = 7;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 1000;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 1000;
i = 8;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 30;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.2;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 20;