% script_inputPipeProperties

i = 1;
    j=1;
    pipe(i,j).tag = 'L1';
    pipe(i,j).c  = 1000; % wave speed
    pipe(i,j).D  = 0.063;  % diameter
    pipe(i,j).f  = 0.03; % friction factor
    pipe(i,j).Nx = 100; % number of reaches
    j=2;
    pipe(i,j).tag = 'L1A';
    pipe(i,j).c  = 1000; % wave speed
    pipe(i,j).D  = 0.063;  % diameter
    pipe(i,j).f  = 0.03; % friction factor
    pipe(i,j).Nx = 500; % number of reaches 
i = 2;
    j=1;
    pipe(i,j).tag = 'L2';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.04;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 20;
    j=2;
    pipe(i,j).tag = 'L2A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.04;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 10;
    %pipe(i).startNode = 4;
    %pipe(i).endNode = 5;
i = 3;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.04;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 20;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.04;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 20;
i = 4;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.01;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 50;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 500;
    pipe(i,j).D  = 0.005;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 10;
i = 5;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.01;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 16;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 500;
    pipe(i,j).D  = 0.003;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 16;
i = 6;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.02;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 40;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.01;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 40;
i = 7;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.02;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 30;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.01;
    pipe(i,j).f  = 0.03;
    pipe(i,j).Nx = 40;
i = 8;
    j=1;
    pipe(i,j).tag = 'L3';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.01;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 200;
    j=2;
    pipe(i,j).tag = 'L3A';
    pipe(i,j).c  = 1000;
    pipe(i,j).D  = 0.005;
    pipe(i,j).f  = 0.02;
    pipe(i,j).Nx = 80;